### ISSUE TITLE
initialize values

### ISSUE THREAD

**Issue by tfhartmann** [huit/perl-check_fortigate_vpn#1]
This script should have slightly better initialization, since at the moment it horks a bit with ePN and devices that have zero sessions configured

**Comment by steven1973** [comment]
to me it does not work and gives me this error: Can not use an undefined value as a HASH reference at. / check_fortigate_vpn.pl line 84. What can 'be? 
There are two days that there are over ..

**Comment by steven1973** [comment]
Help me Please
